### ISSUE TITLE
Add utilities for working with files

### ISSUE THREAD

**Issue by taylorhughes719** [DianoxDragon/Hawn#3]
### Possible utilities:
- A FileWriter (for writing data to files)
- A FileReader (for reading data from files)
- A class named 'FileUtils' in the 'utils' package
- Maybe something for working with JSON files?

#### These are all ideas, and they do **not** need to be implemented.

**Comment by DianoxDragon** [comment]
That might be cool.

**Comment by Drahoxx** [comment]
You can also work with XML files, it's a good way to store data/config very clearly.
(Use XML parser for reading XML files)

**Comment by DianoxDragon** [comment]
That could be interesting.

**Comment by Drahoxx** [comment]
If you want I have created a plugin who allow players to open menu for teleportation to differents servers (in a bungeecord network). I can give you some sources to add to your plugin ?

(ps : I'm sorry if I made some english error, but it's not my mother tongue)

**Comment by DianoxDragon** [comment]
You can if you want to, but I'm not going to put this feature right away... It will be in the beta of the plugin, a fairly advanced beta. 

And I can assure you, English is not my mother tongue either.

**Comment by Drahoxx** [comment]
https://github.com/Drahoxx/D-Hexogane-Lobby

**Comment by Drahoxx** [comment]
(Are you french ? I see that on the web)

**Comment by DianoxDragon** [comment]
Yes i'm french

**Comment by Drahoxx** [comment]
Ah xD ça va être plus simple xD

**Comment by DianoxDragon** [comment]
Il me faudra un autre moyen de contact que Github, évitons de pourrir ce ticket

**Comment by Drahoxx** [comment]
Mon pseudo discord : Drahoxx#6168
(Je vais supprimer mes messages sur le ticket)

**Comment by DianoxDragon** [comment]
Je vous ai demandé j'attend juste confirmation
